Linux: Move files to trash
DeaDBeeF-Player/deadbeef pull request #2441
Opened 2020-09-07 11:02 UTC by kpcee

Instead of deleting files directly the files are moved to the recycle bin with [GIO](https://developer.gnome.org/gio/stable/gio.html) (if available, but should be present in all GTK based distributions).

2020-09-07 16:10 UTC, Alexey-Yakovenko commented
1. It's a nice feature, but I don't like that it's using the command line utility instead of directly calling GIO API.
2. Also not quite sure why it has to be limited to Linux. To my best understanding, it should work on any system where GIO is used, and GTKUI works on BSD and Mac systems.
3. I'm not sure whether it's good or bad idea, but something tells me there will be users who would prefer to delete directly without Trash, e.g. the people who are not using DEs like GNOME or KDE.. there's no UI for Trash access/cleaning. So it seems reasonable to provide an option to delete the files directly. Although having Trash enabled by default is good.

2020-09-07 16:13 UTC, Alexey-Yakovenko commented on plugins/gtkui/actionhandlers.c
> +        snprintf (command, sizeof (command), "/usr/bin/gio trash \"%s\"", uri);
Aside from other comments, using double quotes in this case is unsafe, since the filename can contain a double quote in its name, which would open a possibility of arbitrary code execution in certain scenario.

2020-09-07 17:22 UTC, kpcee commented
> 1. It's a nice feature, but I don't like that it's using the command line utility instead of directly calling GIO API.

Using the API is much easier than expected and the changes are minimal:
```
GFile *file = g_file_new_for_path (uri);
GError *error = NULL;
g_file_trash (file, NULL, &error);
```
> 2. Also not quite sure why it has to be limited to Linux. To my best understanding, it should work on any system where GIO is used, and GTKUI works on BSD and Mac systems (edit: and Windows!).

If it really works on all platforms, an entry in the settings would certainly make sense. I will revise the PR.

2020-09-07 17:25 UTC, Alexey-Yakovenko commented
nice!

2020-09-08 12:53 UTC, kpcee commented
Okay updated.

2020-09-08 13:07 UTC, Alexey-Yakovenko requested changes

2020-09-08 13:07 UTC, Alexey-Yakovenko commented on plugins/gtkui/deadbeef.glade
> +		      <property name="label" translatable="yes">Move files to trash</property>
A better name for this is: "Delete from disk should use Trash"
Otherwise it's completely unclear what this option refers to.

2020-09-08 13:07 UTC, Alexey-Yakovenko commented on plugins/gtkui/actionhandlers.c
> +        const char *buf2 = deadbeef->conf_get_int ("gtkui.move_to_trash", 1) == 1 ? _(" The file(s) will be moved to trash.\n\n(This dialog can be turned off in GTKUI plugin settings)") : _(" The fil
I don't like "file(s)".
It's ok to use "files" even in singular form when there's no specific count displayed.

2020-09-08 13:10 UTC, Alexey-Yakovenko requested changes

2020-09-08 13:10 UTC, Alexey-Yakovenko commented on plugins/gtkui/actionhandlers.c
> +        const char *buf2 = deadbeef->conf_get_int ("gtkui.move_to_trash", 1) == 1 ? _(" The file(s) will be moved to trash.\n\n(This dialog can be turned off in GTKUI plugin settings)") : _(" The fil
`== 1` is unnecessary. It's better to test for "nonzero".
If you prefer explicit equality test, it should be `!= 0`.

2020-09-08 13:10 UTC, Alexey-Yakovenko commented on plugins/gtkui/actionhandlers.c
> +        const char *buf2 = deadbeef->conf_get_int ("gtkui.move_to_trash", 1) == 1 ? _(" The file(s) will be moved to trash.\n\n(This dialog can be turned off in GTKUI plugin settings)") : _(" The fil
It would be great for readability to split this into 3 lines:
```
const char *buf2 = deadbeef->conf_get_int ("gtkui.move_to_trash", 1) == 1 ?
 _(" The file(s) will be moved to trash.\n\n(This dialog can be turned off in GTKUI plugin settings)") :
 _(" The file(s) will be lost.\n\n(This dialog can be turned off in GTKUI plugin settings)");
```

2020-09-08 15:06 UTC, kpcee commented
Okay done.

2020-09-08 15:13 UTC, Alexey-Yakovenko commented
Great. Merging.

2020-09-08 15:13 UTC, merged

2020-09-08 15:14 UTC, Alexey-Yakovenko commented
Great job, thanks for cooperating :)

2020-09-09 11:25 UTC, kpcee commented
Thanks for the kind words.