psf: fix getting a relative directory error on windows
DeaDBeeF-Player/deadbeef pull request #2527
Opened 2021-02-10 14:04 UTC by Greedysky

Fix getting a relative directory error on windows, which causes the file(such as .minidsf .minipsf .miniqsf .minissf) not to be imported

2021-02-10 15:45 UTC, kuba160 commented
DeaDBeeF does converting to forward slash internally, so I looked what causes the problems.

In `eng_psf.c`:
```c
void
ao_getlibpath (const char *path, const char *libname, char *libpath, int size) {
    const char *e = strrchr (path, ':');
    if (!e) {
        e = strrchr (path, '/');
    }
    if (e) {
    ...
```
It checks first if path includes `:` symbol and uses it to separate between file and filepath. If it doesn't it just uses forward slash. I have no idea why it checks for `:`, but it clearly breaks on windows paths. Having it to always use forward slash (`if (1)`) fixes it for local files, but it didn't work for samba paths (starting with `//`).

2021-02-10 15:55 UTC, kuba160 commented
my mistake, I was missing `.psflib` file on samba disk, it works just fine on them. Never used psf before 🙂.

2021-02-10 17:48 UTC, Alexey-Yakovenko requested changes

2021-02-12 13:23 UTC, Greedysky commented on plugins/psf/psfmain.c
> +    const char *e = strrchr (path, 0x5C); // '\\'
I started with '\\'，but there seemed to be a problem on ubuntu 16.04 with gcc 5.4, so I used the ASCII code directly.

2021-02-12 13:25 UTC, Greedysky commented on plugins/psf/psfmain.c
> +ao_getlibpath (const char *path, const char *libname, char *libpath) {
Yes, I agree with you.

2021-02-20 17:24 UTC, Alexey-Yakovenko commented
@Greedysky are you intending to fix the requested changes in this PR?

2021-02-24 01:11 UTC, Greedysky commented
> 
> 
> @Greedysky are you intending to fix the requested changes in this PR?

Done.

2021-02-25 17:27 UTC, merged

2021-02-25 17:27 UTC, Alexey-Yakovenko commented
Thanks!