exec_cmdline implementation + small fixes
DeaDBeeF-Player/deadbeef pull request #2673
Opened 2021-09-16 12:47 UTC by kuba160

Fixes:
- Add premake build files into `.gitignore`
- Fix hardcoded wildcards in `artwork-legacy` (fixes #2494)

exec_cmdline:
- Runs in `server_exec_command_line`
- Gets plugins from `plug_get_list()` and calls `exec_cmdline` if implemented
- Calls every plugin even though some plugin might already have used and processed given arguments. I was unsure what 'right' behavior should be. There might be a case where some broken plugin can pretend to have used arguments and make other plugins not receive `exec_cmdline` calls. From other side this can lead to arguments being interpreted twice. Can change depending on your final opinion.

2021-09-17 15:39 UTC, kuba160 commented on main.c
> +                        if (lseek(fd, 0, SEEK_CUR) && sendback) {
This should use SEEK_END instead of SEEK_CUR

2021-09-20 18:39 UTC, Alexey-Yakovenko requested changes

2021-09-20 18:39 UTC, Alexey-Yakovenko commented on main.c
> +                if (strcmp(plugins[i]->id, plugid) == 0) {
Please use `plug_get_for_id` instead

2021-09-20 21:50 UTC, kuba160 commented
I'll test the changes tomorrow. After that I'm gonna squash all commits related to `exec_cmdline` into one. I also noticed that api version history is wrong in `deadbeef.h` - it says that API 1.13 is for deadbeef 1.9 and we are already on 1.15 🙂.

2021-09-21 06:11 UTC, Alexey-Yakovenko commented
> I also noticed that api version history is wrong in deadbeef.h - it says that API 1.13 is for deadbeef 1.9 and we are already on 1.15 🙂.

I noticed that too, it's already corrected on medialib branch. There's no need to change it on master right now.

2021-09-21 12:09 UTC, kuba160 commented
I tested the implementation and applied small adjustments. All commits related to `exec_cmdline` have been merged into one. The original branch can be found here: https://github.com/DeaDBeeF-for-Windows/deadbeef/tree/cmdline

Example implementation of `exec_cmdline` can be found here (plugin cust_seek, branch cmdline): https://github.com/kuba160/ddb_cust_seek/blob/83724e08cb24b8f7adbce240a857c404bce04ab2/cust_seek.c#L142

2021-09-21 16:34 UTC, merged

2021-09-21 16:35 UTC, Alexey-Yakovenko commented
@kuba160 
Please note: I don't guarantee that the API will stay unchanged in the next release. I'll notify you about any changes, as necessary.