tf: implement and test $get(), $put(), and $puts()
DeaDBeeF-Player/deadbeef pull request #2978
Opened 2023-08-05 13:42 UTC by rsekman

2023-08-05 15:42 UTC, Oleksiy-Yakovenko requested changes
First round of review:
Overall makes sense, so no big changes requested - mostly stylistic.
After the code is cleaned up I'll do a 2nd round + testing / validation.

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +    char* key;
Deadbeef uses coding convention where the `*` is placed on the right hand side, so please correct in the new code -- it should look like this `char *key` etc

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +tf_var_new(const char* key, const char* value){
It would be more explicit and more performant to convert this code to be initializer style, i.e. pass a pointer to the struct as argument, and initialize it there.
Then the calls would like this: `tf_var_init(&var, key, value)`, and there would not be unnecessary copying.

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +tf_var_free(ddb_tf_var_t var) {
Same here, this function looks like it would free an object, but really -- this is a "deinitializer" (also known as destructor), it is preferred to call these "deinit: `tf_var_deinit(&var)`

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +char*
This function should be returning `const char *`

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +    char* tmpkey = malloc(strlen(key)+1);
I don't see any reason for this tmpkey variable

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +        if (!u8_strcasecmp (tmpkey, vars->var.key)) {
According to foobar2000 specification, the variables are case-sensitive, so you should be using strcmp instead.

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +    ddb_tf_vars_t* out = malloc(sizeof(ddb_tf_var_t));
It's preferred to use calloc, to automatically initialize the allocated memory with zeroes

2023-08-05 15:42 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +        tf_vars_free(vars->next);
It's completely unnecessary to use recursion here.
It's less efficient, harder to read, and potentially may cause stack overflow if the list is large enough.

2023-08-05 15:45 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +        if (!u8_strcasecmp (tmpkey, vars->var.key)) {
sorry, I got confused and misread the spec. Please ignore this comment.

2023-08-05 15:46 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +        char* value = tf_vars_lookup(priv->vars, temp_key);
This line causes "unused variable" compiler warning

2023-08-05 15:47 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +tf_func_put_ (ddb_tf_context_t *ctx, int argc, const uint16_t *arglens, const char *args, char *out, int outlen, int fail_on_undef, int should_return) {
It's non-conventional in deadbeef to have `_` suffix in function names. What does it mean here?

2023-08-05 15:48 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +tf_func_put_ (ddb_tf_context_t *ctx, int argc, const uint16_t *arglens, const char *args, char *out, int outlen, int fail_on_undef, int should_return) {
(it seems like it's an internal / private function. In this case you need to add `static` to it, and use prefix `_` instead of suffix.

2023-08-05 15:51 UTC, rsekman commented on src/tf.c
> +tf_func_put_ (ddb_tf_context_t *ctx, int argc, const uint16_t *arglens, const char *args, char *out, int outlen, int fail_on_undef, int should_return) {
The only difference between `$put` and `$puts` is whether the stored value should be returned. So it is DRY to to have an internal function that takes an extra `bool should_return`. Fixed.

2023-08-05 15:53 UTC, rsekman commented on src/tf.c
> +        char* value = tf_vars_lookup(priv->vars, temp_key);
It is also superfluous. Fixed.

2023-08-05 15:55 UTC, rsekman commented on src/tf.c
> +    char* tmpkey = malloc(strlen(key)+1);
Mistake left over, fixed.

2023-08-05 16:31 UTC, rsekman commented on src/tf.c
> +tf_var_new(const char* key, const char* value){
You mean copying of the struct, not the strings, right? Because the strings are going to be read into buffers of size `TEMP_BUFFER_SIZE` on the stack. The buffers could, of course, be put on the heap. But we can't know how long they are before evaluating them, so we should shrink to fit with `realloc` anyway... this should not be the responsibility of the caller. So keep `strcpy` in the body, yes?

2023-08-05 16:33 UTC, Oleksiy-Yakovenko commented on src/tf.c
> +tf_var_new(const char* key, const char* value){
I mean this:

```
void
 tf_var_init(ddb_tf_var_t *var, const char* key, const char* value) {
    var->key = strdup(key);
    var->value = strdup(value);
}
```

2023-08-19 17:07 UTC, Oleksiy-Yakovenko commented
@rsekman hey, are you planning to finalize the PR?
It seems like it's failing on some unit tests, which use too little buffer space (8 bytes). You should replace all those buffer size parameters with `sizeof(buffer)` to fix it.
However, the tests also don't finish even if I fix this, and they cause memory corruption.
I think your linked list code is not right.

2023-08-19 17:13 UTC, Oleksiy-Yakovenko commented
(I'll try to fix it on my own, since I think explaining what needs to be fixed will take longer time)

2023-08-19 17:29 UTC, closed without merging

2023-08-19 18:08 UTC, rsekman commented
Hmm, the tests pass on Linux but not on Mac. I don't know why that would be and don't have a Mac to test with. UTF-8 vs UTF-16?

2023-08-19 18:09 UTC, Oleksiy-Yakovenko commented
I have already refactored / fixed / tested / merged everything, so nothing left to do - unless you find some more issues.