support relative paths when loading DBPL playlists
DeaDBeeF-Player/deadbeef pull request #3115
Opened 2024-08-24 16:40 UTC by rsekman

related to: https://github.com/DeaDBeeF-Player/deadbeef/issues/1798

when loading an M3U playlist deadbeef supports interpreting the paths relative to the location of the playlist file. this feature is currently missing from the code loading native (DBPL) playlists, but is implemented in this pull request.

this PR will not pass CI due to a segmentation fault in the Playlist test suite. the segmentation fault occurs only if the Playlist test suite is not run first. that is, 
```sh
./scripts/test.sh Playlist AlbumNavigation #passes
./scripts/test.sh AlbumNavigation Playlist #segfaults
```
the segfault occurs here, when  checking if loading the playlist should be handled by a plugin:
https://github.com/DeaDBeeF-Player/deadbeef/blob/a50e3a54261abcfcd8a4e627edc3a8b94ace6aff/src/playlist.c#L2707-L2711
if the Playlist test suite is run first, the array `plug` is empty (`plug[0] == NULL`), but if not it contains an invalid pointer. I do not understand why this happens and don't know how to trace it further.

2024-08-24 18:35 UTC, Oleksiy-Yakovenko requested changes

2024-08-24 18:35 UTC, Oleksiy-Yakovenko commented on src/playlist.c
> +    char dname[PATH_MAX] = "";
It's better to dynamically allocate this one, since stack can get fairly deep with unpredictable memory needs.

2024-08-24 18:35 UTC, Oleksiy-Yakovenko commented on src/playlist.c
> +        char true_uri[PATH_MAX];
This should be moved to the scope where it's used, to avoid unnecessary stack memory consumption after this variable is not needed. Also, it's safer to dynamically allocate it.

2024-08-24 18:35 UTC, Oleksiy-Yakovenko commented on src/playlist.c
> +                        if (strcmp (key, ":URI") != 0) {
Why is this change necessary?

2024-08-24 18:38 UTC, Oleksiy-Yakovenko commented
> this PR will not pass CI due to a segmentation fault in the Playlist test suite. the segmentation fault occurs only if the Playlist test suite is not run first. that is,

This seems like some sort of test setup problem. I'm sure I'll be able to figure it out, but I'm a bit time constrained in the next few weeks.
I'll try to debug it as soon as I can.

2024-08-25 00:08 UTC, rsekman commented on src/playlist.c
> +                        if (strcmp (key, ":URI") != 0) {
Otherwise a stored `:URI` value will overwrite the value read and interpreted as a relative path before. But it would be better to process this value the same way, I suppose.

2024-08-25 00:43 UTC, rsekman commented on src/playlist.c
> +        char true_uri[PATH_MAX];
Resolved by factoring the subsequent logic into a function which returns a pointer to a dynamically allocated string; it is the caller's responsibility to `free()` it. This function can then be reused to address the next comment.

2024-08-25 09:41 UTC, Oleksiy-Yakovenko commented on src/playlist.c
> +                        if (strcmp (key, ":URI") != 0) {
ok, I understand a bit better now.. I misread what the if condition was originally.

2024-08-25 09:45 UTC, Oleksiy-Yakovenko commented on src/playlist.c
> +    if (dname) {
nit: this "if" is unnecessary, the `free` will do this check automatically.

2024-08-27 01:07 UTC, rsekman commented on src/playlist.c
> +    if (dname) {
Fixed; also fixed that `goto`:s could lead to reaching this without `dname` being initialised. (Caught by the Mac CI but passed on Linux, must be some compiler difference?)

2024-09-07 15:44 UTC, Oleksiy-Yakovenko commented
I fixed the issue with tests and merged everything to master.

2024-09-07 15:44 UTC, closed without merging